const canvas=document.getElementById('particles'),ctx=canvas.getContext('2d'),button=document.getElementById('pause');
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduce.matches,w=0,h=0,t=0,raf=0,last=0;const pointer={x:0,y:0,active:false};
const points=Array.from({length:140},(_,i)=>({a:i*2.39996,r:Math.sqrt((i+.5)/140),phase:i*.83}));
function size(){const box=canvas.getBoundingClientRect();w=box.width;h=box.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);draw()}
let quantumPulse=null;
function draw(){ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,r=Math.min(w*.31,h*.34),yaw=t*.24+(pointer.active?(pointer.x/w-.5)*1.8:0),tilt=.35+(pointer.active?(pointer.y/h-.5)*.8:0);const core=ctx.createRadialGradient(cx,cy,0,cx,cy,r*1.65);core.addColorStop(0,'rgba(98,164,255,.21)');core.addColorStop(.35,'rgba(72,132,235,.08)');core.addColorStop(1,'rgba(30,80,170,0)');ctx.fillStyle=core;ctx.fillRect(0,0,w,h);
function project(x,y,z){const xx=x*Math.cos(yaw)-z*Math.sin(yaw),zz=x*Math.sin(yaw)+z*Math.cos(yaw),yy=y*Math.cos(tilt)-zz*Math.sin(tilt),depth=y*Math.sin(tilt)+zz*Math.cos(tilt),scale=3.8/(3.8-depth);return{x:cx+xx*r*scale,y:cy+yy*r*scale,z:depth,scale};}
const sphere=Array.from({length:220},(_,i)=>{const yy=1-2*(i+.5)/220,rr=Math.sqrt(1-yy*yy),angle=i*2.39996+t*.12;return project(Math.cos(angle)*rr,yy,Math.sin(angle)*rr);}).sort((a,b)=>a.z-b.z);
for(let ring=0;ring<4;ring++){ctx.beginPath();for(let i=0;i<=140;i++){const angle=i/140*Math.PI*2+t*(ring%2?-.16:.16),x=Math.cos(angle)*1.22,y=Math.sin(angle)*1.22;const p=project(x,y*Math.cos(ring*.75),y*Math.sin(ring*.75));i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);}ctx.strokeStyle=ring%2?'rgba(226,191,126,.35)':'rgba(123,190,255,.38)';ctx.lineWidth=1;ctx.stroke();for(let dot=0;dot<3;dot++){const angle=t*(.6+ring*.11)+dot*Math.PI*2/3,p=project(Math.cos(angle)*1.22,Math.sin(angle)*1.22*Math.cos(ring*.75),Math.sin(angle)*1.22*Math.sin(ring*.75));ctx.shadowBlur=15;ctx.shadowColor=ring%2?'#dfc28c':'#8bcaff';ctx.fillStyle=ctx.shadowColor;ctx.beginPath();ctx.arc(p.x,p.y,2.6*p.scale,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
sphere.forEach((p,i)=>{if(i%3===0){for(let j=i+1;j<Math.min(i+17,sphere.length);j++){const q=sphere[j],dist=Math.hypot(p.x-q.x,p.y-q.y);if(dist<r*.27){ctx.strokeStyle=`rgba(135,190,252,${(1-dist/(r*.27))*.19*(p.z+1.5)/2.5})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}}ctx.fillStyle=i%13===0?'#f2d7a4':`rgba(153,208,255,${.3+(p.z+1)*.3})`;ctx.beginPath();ctx.arc(p.x,p.y,(i%13===0?2:1.15)*p.scale,0,Math.PI*2);ctx.fill();});
ctx.shadowBlur=24;ctx.shadowColor='#86bcff';ctx.fillStyle='#eaf4ff';ctx.beginPath();ctx.arc(cx,cy,3.5+Math.sin(t*1.8)*.7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
if(quantumPulse){const age=t-quantumPulse.time;if(age>1.6)quantumPulse=null;else{ctx.strokeStyle=`rgba(239,205,143,${(1-age/1.6)*.8})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(quantumPulse.x,quantumPulse.y,8+age*r*2,0,Math.PI*2);ctx.stroke();}}
}
canvas.addEventListener('pointerdown',e=>{if(paused||reduce.matches)return;const box=canvas.getBoundingClientRect();quantumPulse={x:e.clientX-box.left,y:e.clientY-box.top,time:t};});
function frame(now){if(paused||document.hidden){raf=0;return}if(last)t+=Math.min((now-last)/1000,.05);last=now;draw();raf=requestAnimationFrame(frame)}
function sync(){button.textContent=document.documentElement.lang==='zh-Hant'?(paused?'繼續動畫':'暫停動畫'):(paused?'Resume motion':'Pause motion');button.setAttribute('aria-pressed',String(paused));cancelAnimationFrame(raf);raf=0;last=0;if(!paused&&!document.hidden)raf=requestAnimationFrame(frame);else draw()}
button.addEventListener('click',()=>{paused=!paused;sync()});canvas.addEventListener('pointermove',e=>{const b=canvas.getBoundingClientRect();pointer.x=e.clientX-b.left;pointer.y=e.clientY-b.top;pointer.active=true;if(paused)draw()});canvas.addEventListener('pointerleave',()=>{pointer.active=false;if(paused)draw()});canvas.addEventListener('pointerup',e=>{if(e.pointerType!=='mouse'){pointer.active=false;if(paused)draw()}});document.addEventListener('visibilitychange',sync);reduce.addEventListener('change',e=>{paused=e.matches;sync()});new ResizeObserver(size).observe(canvas);size();sync();
const translations={
'05 / AI & THE FUTURE':'05 / AI 與未來','What remains distinctly human?':'何以為人？','As AI becomes part of every field, how might it reshape what we consider distinctly human?':'當 AI 進入每一個領域，它將如何改變我們對「人之獨特性」的理解？','HUMAN + AI':'人 + AI','Shared activities. New questions.':'共同的活動，新的追問。','Create':'創造','Know':'認知','Judge':'判斷','Authorship & intention':'作者身分與意圖','Knowledge & understanding':'知識與理解','Values & responsibility':'價值與責任','MEDIA & STORYTELLING':'媒體與敘事','If creation is shared, where does authorship begin?':'當創作由人與 AI 共同完成，作者身分從何而來？','I want to explore how intention, interpretation and creative ownership change when people create with AI.':'我希望探索：當人與 AI 一起創作，意圖、詮釋與創作歸屬如何改變。','Human agency & responsibility':'人的自主性與責任','How do we remain authors of our choices?':'我們如何仍然是自身選擇的作者？','A direction I hope to explore through further study, grounded in my media work, storytelling and practical tools.':'這是我希望透過進一步學習探索的方向，從我的媒體、敘事與實用工具經驗出發。','INFORMATION & UNDERSTANDING':'資訊與理解','If AI provides an answer, what does it mean to know?':'當 AI 提供答案，「知道」意味著什麼？','I want to explore the difference between receiving an answer and understanding its evidence, assumptions and limits.':'我希望探索：獲得答案與理解其證據、假設及局限，兩者有何差別。','DECISIONS & ACCOUNTABILITY':'決策與責任','If a decision is assisted by AI, who is responsible?':'當決策由 AI 輔助，責任由誰承擔？','I want to explore how people can retain agency and take responsibility for decisions shaped by AI recommendations.':'我希望探索：當 AI 建議影響決策，人如何保有自主性並承擔責任。','06 / CONTACT':'06 / 聯絡',

'The University of Newcastle, Australia':'澳洲紐卡斯爾大學','Bachelor of Communication':'傳播學學士','with Distinction':'優異成績畢業','Majors in News Media and Public Relations':'雙主修：新聞媒體與公共關係','Awarded and conferred: 05 September 2024':'學位授予日期：2024 年 9 月 5 日','2023 / ACADEMIC RECOGNITION':'2023 / 學術表彰','College Commendation List':'學院表彰名單','College of Human and Social Futures':'人文與社會未來學院',

'04 / AI collaboration':'04 / AI 協作','I used AI to organise requirements, design the calculation logic, write code and debug the tool.':'我使用 AI 整理需求、設計計算邏輯、編寫程式碼，並協助工具除錯。',
'AI PRACTICE / A TOOL I BUILT':'AI 實踐 / 我搭建的工具','Turning budgets into scenarios.':'將預算轉化為情境。','An independently built tool for forecasting social-commerce advertising budgets and conversions.':'我獨立搭建的社媒電商廣告預算與轉化預測工具。','Built around a real planning question.':'從真實的規劃問題出發。','I built this tool to explore advertising budgets and conversion forecasts for social-commerce planning.':'我搭建這個工具，用於探索社媒電商的廣告預算與轉化預測。','01 / Inputs':'01 / 輸入','02 / Data':'02 / 數據','03 / Planning':'03 / 規劃','Budget, forecast period, average order value and per-order costs are brought into one interface.':'將預算、預測週期、平均訂單金額與每單成本整合在同一介面。','The tool provides daily CSV import and an option for handling outliers.':'工具提供每日 CSV 匯入與異常值處理選項。','Adjustable assumptions provide a structured way to explore different planning scenarios.':'透過調整假設，有條理地探索不同規劃情境。','View interface':'查看介面',

'An independent AI short-drama project. All creative work is my own.':'這是一項獨立 AI 短劇創作，所有創作工作均由我獨立完成。','CREATIVE DEVELOPMENT / NOT YET RELEASED':'創作階段 / 尚未播出','Watermarked preview / Application only.':'浮水印預覽 / 僅供申請使用。',
'04 / AI CREATIVE PRACTICE':'04 / AI 創作實踐','From characters to scenes.':'從角色走向場景。','A behind-the-scenes look at my AI short-drama creative process.':'走進我的 AI 短劇創作過程。','Characters':'角色','Voice':'聲音','Storyboard':'分鏡','Generation':'生成','01 / CHARACTERS':'01 / 角色','Building a consistent cast.':'建立一致的角色設定。','Character sheets bring portraits, full-body views, clothing and written profiles into one workspace.':'角色設定卡將肖像、全身視圖、服裝與文字設定整合在同一工作空間。','PROCESS STUDY / IN DEVELOPMENT':'創作過程 / 製作中','View full workspace':'查看完整工作空間','02 / SELECTED MEDIA WORKS':'02 / 精選媒體作品','05 / CONTACT':'05 / 聯絡',
'02 / VOICE':'02 / 聲音','Giving each character a voice.':'為角色建立聲音。','Voice previews sit alongside character references, making it possible to compare sound with the intended character.':'聲音試聽與角色參考並列，便於對照聲音與角色設定。','03 / STORYBOARD':'03 / 分鏡','Planning the visual sequence.':'規劃視覺敘事。','Storyboard cards organise scene descriptions, shot directions and durations before individual clips are assembled.':'分鏡卡整理場景描述、鏡頭方向與時長，作為後續影片製作的規劃。','04 / GENERATION':'04 / 生成','Moving from plans to clips.':'從規劃走向鏡頭生成。','The project is in creative development and has not been released. A watermarked preview is shared here for application purposes only.':'項目仍處於創作階段，尚未播出。此處僅提供供申請使用的浮水印預覽。',

'Selected news and podcast work from my media studies.':'精選我在媒體學習期間製作的新聞與播客作品。','MANDARIN / PODCAST':'普通話 / 播客','Confronting Diabetes in Singapore':'直面新加坡的糖尿病問題',
'I am Jerry. My academic background is in media.':'我是 Jerry。我過去學習的領域是媒體。',
'My English-language news work is part of that journey. This portfolio brings together my media work and my growing interest in AI and the future.':'這些英文新聞作品是我學習歷程的一部分。這個作品集結合了我的媒體作品，以及我對人工智能與未來逐漸加深的興趣。',
'02 / SELECTED MEDIA WORKS':'02 / 精選媒體作品','Stories, in focus.':'聚焦故事。','A selection of my English-language news work from my media studies.':'精選我在媒體學習期間製作的英文新聞作品。','ENGLISH / NEWS':'英文 / 新聞','Mini News Bulletin':'迷你新聞播報','Edited Interview':'剪輯訪談','News Data Visualization':'新聞數據視覺化','Watch on YouTube':'在 YouTube 觀看','Open video':'開啟影片',

'This website is intended solely for university application purposes.':'本網頁僅供大學申請使用。',
'FOLLOW YOUR CURIOSITY':'跟隨你的好奇心',
'/ PORTFOLIO':'/ 個人作品集','About':'關於我','Explore':'探索','Work':'作品','Contact':'聯絡',
'ARTIFICIAL INTELLIGENCE × FUTURE DEVELOPMENT':'人工智能 × 未來發展','Exploring intelligence.':'探索智能。','Imagining what comes next.':'想像未來的可能。',
'A personal portfolio for my journey towards AI and future development at Lingnan University.':'記錄我申請嶺南大學、探索人工智能與未來發展的個人作品集。',
'Explore the interaction':'探索互動體驗','Get in touch':'與我聯絡','Replay intro':'重播開場','01 / THE PERSON':'01 / 個人','CURIOUS ABOUT THE FUTURE':'對未來保持好奇','PERSONAL PORTFOLIO / 2026':'個人作品集 / 2026',
'01 / ABOUT':'01 / 關於我','Technology begins':'科技始於','with a question.':'一個提問。','I am Jerry.':'我是 Jerry。',
'This portfolio is a place to bring together my projects, learning and ideas as I develop them.':'這個作品集將逐步匯集我的項目、學習歷程與想法。','03 / INTERACTIVE STUDY':'03 / 互動實驗','A field of possibilities.':'一片可能性的場域。',
'Move your pointer or touch the field to influence its motion. A small experiment in interaction and generative visuals.':'移動游標或觸碰畫面，改變光點的流動。這是一個探索互動與生成式視覺的小實驗。',
'PARTICLE FIELD / LIVE INTERACTION':'粒子場 / 即時互動','Pause motion':'暫停動畫','Resume motion':'繼續動畫','QUANTUM-INSPIRED VISUAL STUDY':'量子意象視覺實驗','Move · Touch · Explore':'移動 · 觸碰 · 探索',
'An artistic particle visualization, inspired by quantum imagery. It does not simulate a physical quantum system.':'以量子意象為靈感的藝术粒子視覺，並非真實量子系統的物理模擬。',
'03 / WORK IN PROGRESS':'03 / 持續探索','Room for what comes next.':'為下一步留下空間。','This is the starting framework. Project details and reflections will be added as they are ready.':'這是作品集的初步框架，項目詳情與思考將在準備完成後加入。',
'THIS WEBSITE':'本網站','Personal portfolio':'個人作品集','A first space for sharing my work, with an interactive particle experiment and a responsive design.':'分享作品的第一個空間，結合互動粒子實驗與適配不同裝置的設計。','First version':'初版',
'FUTURE PROJECT':'未來項目','AI exploration':'人工智能探索','A space reserved for a future project: the question, process, outcome and what I learned.':'預留給未來項目：從提問、過程到成果，以及我從中學到的事。','To be added':'待補充',
'FUTURE REFLECTION':'未來思考','Technology & society':'科技與社會','A space reserved for my reflections on how AI might shape our shared future.':'預留給我的思考：人工智能將如何塑造我們共同的未來。',
'04 / CONTACT':'04 / 聯絡','Let’s start a conversation.':'讓我們展開對話。','Back to top':'返回頂部','THE SPARK OF POSSIBILITY':'點亮未來的火種','Carry the spark. Ignite the flame.':'讓火種點亮火焰。','Move the spark to ignite':'移動火種，點亮火焰','Enter portfolio':'進入作品集','With gentle ambient sound':'伴隨輕柔空靈配樂','Sound off':'聲音關閉','Sound on':'聲音開啟','Skip intro':'跳過開場',
'Sound unavailable · Enjoy the visual experience':'無法播放聲音 · 仍可欣賞視覺體驗','Carry the spark to the flame':'將火種帶到雕像手中的火焰','Drag the spark to the flame · or press Enter':'拖動火種至火焰 · 或按 Enter' 
};
let currentLanguage='en';
const languageNodes=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let textNode;while(textNode=walker.nextNode()){const value=textNode.textContent.trim();if(translations[value])languageNodes.push({node:textNode,en:value,zh:translations[value]});}
function tr(value){return currentLanguage==='zh-Hant'?(translations[value]||value):value;}
const accessibleTexts=[['nav','Main navigation','主要導覽'],['#welcome-game','Interactive mythology-inspired introduction','西方古典神話意象互動開場'],['#particles','Interactive abstract particle field','互動抽象粒子場'],['#myth-field','Interactive celestial particles','互動星光粒子']];
function applyLanguage(){document.documentElement.lang=currentLanguage;languageNodes.forEach(item=>item.node.textContent=currentLanguage==='zh-Hant'?item.zh:item.en);document.querySelectorAll('.language-toggle').forEach(b=>{b.textContent=currentLanguage==='en'?'繁體中文':'English';b.setAttribute('aria-label',currentLanguage==='en'?'Switch to Traditional Chinese':'切換至英文');});accessibleTexts.forEach(([selector,en,zh])=>document.querySelector(selector)?.setAttribute('aria-label',currentLanguage==='en'?en:zh));document.getElementById('myth-art').alt=currentLanguage==='en'?'Classical marble sculpture holding a golden flame beneath a cosmic sky':'星空下手持金色火種的古典大理石雕像';document.querySelector('.portrait-wrap img').alt=currentLanguage==='en'?'Portrait of Le Quanwei （Jerry Lok）':'Le Quanwei （Jerry Lok）的個人照片';document.querySelector('meta[name=description]').content=currentLanguage==='en'?'Le Quanwei （Jerry Lok） — a personal portfolio exploring artificial intelligence and future development.':'Le Quanwei （Jerry Lok）的個人作品集，探索人工智能與未來發展。';button.textContent=tr(paused?'Resume motion':'Pause motion');document.querySelector('.myth-hint').textContent=tr(gameArmed?'Drag the spark to the flame · or press Enter':'Carry the spark. Ignite the flame.');updateSoundLabel();if(typeof renderCaseStage==='function')renderCaseStage();if(typeof renderThought==='function')renderThought();}
document.querySelectorAll('.language-toggle').forEach(b=>b.addEventListener('click',()=>{currentLanguage=currentLanguage==='en'?'zh-Hant':'en';applyLanguage();}));
const intro=document.getElementById('welcome-game'),mythCanvas=document.getElementById('myth-field'),mc=mythCanvas.getContext('2d'),scene=document.querySelector('.myth-scene'),begin=document.getElementById('begin-intro'),enter=document.getElementById('enter-game'),soundButton=document.getElementById('intro-sound');
let mw=0,mh=0,mythRaf=0,start=0,elapsed=0,running=false,previousFocus=null,audioContext=null,master=null,soundOn=false,musicEnabled=true,noteTimer=null,voiceStep=0,voiceNodes=[];const mouse={x:.5,y:.5,active:false};let gameArmed=false,ignited=false,igniteStart=0,closeTimer=null;const trail=[];
const starSeeds=Array.from({length:170},(_,i)=>({x:((i*73.71)%997)/997,y:((i*41.93)%991)/991,depth:.4+(i%9)/12,phase:i*1.43}));
function updateSoundLabel(){soundButton.textContent=tr(musicEnabled?'Sound on':'Sound off');soundButton.setAttribute('aria-pressed',String(musicEnabled));}
function playNote(frequency,time,duration=2.8){if(!audioContext||!master)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(.065,time+.028);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(gain);gain.connect(master);osc.start(time);osc.stop(time+duration+.05);voiceNodes.push(osc);osc.onended=()=>{osc.disconnect();gain.disconnect();voiceNodes=voiceNodes.filter(x=>x!==osc);};}
function scheduleNotes(){if(!soundOn||!audioContext)return;const melody=[523.25,783.99,1046.5,659.25,880,783.99,587.33,1174.66];const now=audioContext.currentTime;playNote(melody[voiceStep%melody.length],now+.02,2.4);if(voiceStep%4===0)playNote(261.63,now+.1,3.2);voiceStep++;noteTimer=setTimeout(scheduleNotes,voiceStep%3===0?1100:780);}
async function startSound(){try{if(!audioContext){audioContext=new(window.AudioContext||window.webkitAudioContext)();master=audioContext.createGain();master.gain.value=.48;const dry=audioContext.createGain();dry.gain.value=.7;master.connect(dry);dry.connect(audioContext.destination);const delay=audioContext.createDelay(2),feedback=audioContext.createGain(),wet=audioContext.createGain(),filter=audioContext.createBiquadFilter();delay.delayTime.value=.47;feedback.gain.value=.28;wet.gain.value=.32;filter.type='lowpass';filter.frequency.value=3400;master.connect(delay);delay.connect(filter);filter.connect(wet);wet.connect(audioContext.destination);filter.connect(feedback);feedback.connect(delay);}await audioContext.resume();if(!intro.open||document.hidden||!musicEnabled)return;if(!soundOn){soundOn=true;master.gain.cancelScheduledValues(audioContext.currentTime);master.gain.setTargetAtTime(.48,audioContext.currentTime,.12);scheduleNotes();}updateSoundLabel();}catch{soundOn=false;updateSoundLabel();soundButton.title=tr('Sound unavailable · Enjoy the visual experience');}}
function stopSound(){soundOn=false;clearTimeout(noteTimer);noteTimer=null;if(audioContext&&master){master.gain.cancelScheduledValues(audioContext.currentTime);master.gain.setTargetAtTime(0,audioContext.currentTime,.04);}updateSoundLabel();}
function disposeAudio(){stopSound();const old=audioContext;voiceNodes.forEach(v=>{v.onended=null;try{v.stop();}catch{}});voiceNodes=[];audioContext=null;master=null;voiceStep=0;if(old)old.close().catch(()=>{});}
function drawMyth(time){mc.clearRect(0,0,mw,mh);const reveal=Math.min(1,time/4),burst=Math.max(0,1-Math.abs(time-3.4)/1.8);const cx=mw*.5,cy=mh*.38;starSeeds.forEach((s,i)=>{let x=s.x*mw,y=s.y*mh;const spread=1+burst*s.depth*.3;x=cx+(x-cx)*spread;y=cy+(y-cy)*spread;if(mouse.active){x+=(mouse.x-.5)*24*s.depth;y+=(mouse.y-.5)*18*s.depth;}const alpha=.2+reveal*.35+Math.sin(time*.7+s.phase)*.12;mc.fillStyle=i%4===0?`rgba(238,204,143,${alpha})`:`rgba(163,204,255,${alpha})`;mc.beginPath();mc.arc(x,y,s.depth*(i%7===0?2:1),0,Math.PI*2);mc.fill();if(reveal>.3&&i%5===0){const q=starSeeds[(i+11)%starSeeds.length];const d=Math.hypot(s.x-q.x,s.y-q.y);if(d<.28){mc.strokeStyle=`rgba(143,190,244,${reveal*.12})`;mc.beginPath();mc.moveTo(x,y);mc.lineTo(q.x*mw,q.y*mh);mc.stroke();}}});if(burst>0){const gradient=mc.createRadialGradient(cx,cy,0,cx,cy,Math.max(mw,mh)*.4);gradient.addColorStop(0,`rgba(253,219,158,${burst*.2})`);gradient.addColorStop(1,'rgba(253,219,158,0)');mc.fillStyle=gradient;mc.fillRect(0,0,mw,mh);}drawFireGame();}
function mythLoop(now){if(!intro.open||document.hidden){mythRaf=0;return;}if(running){elapsed=Math.min(6.5,(now-start)/1000);if(elapsed>=6.5){running=false;intro.classList.add('complete');enter.hidden=false;}}drawMyth(elapsed);if(running||gameArmed||ignited)mythRaf=requestAnimationFrame(mythLoop);else mythRaf=0;}
function resizeMyth(){const b=mythCanvas.getBoundingClientRect();mw=b.width;mh=b.height;const d=Math.min(devicePixelRatio||1,2);mythCanvas.width=Math.round(mw*d);mythCanvas.height=Math.round(mh*d);mc.setTransform(d,0,0,d,0,0);drawMyth(elapsed);}
function openIntro(){previousFocus=document.activeElement;cancelAnimationFrame(mythRaf);disposeAudio();elapsed=0;running=false;gameArmed=false;ignited=false;clearTimeout(closeTimer);trail.length=0;intro.classList.remove('playing','complete','armed','ignited','departing');document.querySelector('.myth-hint').textContent=tr('Carry the spark. Ignite the flame.');begin.hidden=false;enter.hidden=true;intro.showModal();resizeMyth();}
function flameTarget(){const image=document.getElementById('myth-art'),rect=image.getBoundingClientRect(),board=mythCanvas.getBoundingClientRect();const iw=image.naturalWidth||1536,ih=image.naturalHeight||1024,scale=Math.max(mw/iw,mh/ih),position=getComputedStyle(image).objectPosition.split(' '),px=parseFloat(position[0])/100,py=parseFloat(position[1])/100,sx=rect.width/mw,sy=rect.height/mh;return{x:rect.left-board.left+(iw*(465/1536)*scale+(mw-iw*scale)*px)*sx,y:rect.top-board.top+(ih*(180/1024)*scale+(mh-ih*scale)*py)*sy};}
function drawFireGame(){if(!gameArmed&&!ignited)return;const target=flameTarget();const now=performance.now()/1000;const tx=target.x,ty=target.y;if(!ignited){mc.strokeStyle='rgba(255,216,139,.65)';mc.lineWidth=1.4;mc.beginPath();mc.arc(tx,ty,28+Math.sin(now*3)*5,0,Math.PI*2);mc.stroke();const px=mouse.x*mw,py=mouse.y*mh;trail.push({x:px,y:py});if(trail.length>20)trail.shift();trail.forEach((p,i)=>{mc.fillStyle=`rgba(255,${140+i*4},65,${i/trail.length*.45})`;mc.beginPath();mc.arc(p.x,p.y,1+i/trail.length*5,0,Math.PI*2);mc.fill();});const glow=mc.createRadialGradient(px,py,0,px,py,38);glow.addColorStop(0,'rgba(255,241,184,.9)');glow.addColorStop(.22,'rgba(255,186,74,.65)');glow.addColorStop(1,'rgba(255,137,33,0)');mc.fillStyle=glow;mc.fillRect(px-38,py-38,76,76);mc.fillStyle='#fff3cb';mc.beginPath();mc.ellipse(px,py-4,4,9+Math.sin(now*10)*2,.2,0,Math.PI*2);mc.fill();}else{const age=(performance.now()-igniteStart)/1000;for(let i=0;i<100;i++){const angle=i*2.39996,dist=age*(150+(i%11)*25);const x=tx+Math.cos(angle)*dist,y=ty+Math.sin(angle)*dist;mc.fillStyle=`rgba(255,${195+i%50},125,${Math.max(0,1-age/2.3)})`;mc.beginPath();mc.arc(x,y,2+i%3,0,Math.PI*2);mc.fill();}const flash=Math.max(0,1-age/.5);mc.fillStyle=`rgba(255,235,183,${flash*.82})`;mc.fillRect(0,0,mw,mh);mc.strokeStyle=`rgba(255,222,157,${Math.max(0,.8-age*.3)})`;mc.lineWidth=3;mc.beginPath();mc.arc(tx,ty,age*600,0,Math.PI*2);mc.stroke();}}
function ignite(){if(!gameArmed||ignited)return;gameArmed=false;ignited=true;igniteStart=performance.now();intro.classList.remove('armed');intro.classList.add('ignited');if(soundOn&&audioContext){[523.25,659.25,783.99,1046.5].forEach((f,i)=>playNote(f,audioContext.currentTime+i*.12,2));}closeTimer=setTimeout(()=>{intro.classList.add('departing');closeTimer=setTimeout(()=>{intro.close();location.hash='home';document.querySelector('main').classList.remove('arrival');requestAnimationFrame(()=>document.querySelector('main').classList.add('arrival'));},reduce.matches?0:650);},reduce.matches?350:1450);}
begin.addEventListener('click',()=>{if(musicEnabled)startSound();begin.hidden=true;gameArmed=true;scene.style.setProperty('--mx','0px');scene.style.setProperty('--my','0px');mouse.x=.5;mouse.y=.72;mouse.active=true;intro.classList.add('armed');document.querySelector('.myth-hint').textContent=tr('Drag the spark to the flame · or press Enter');mythCanvas.tabIndex=0;mythCanvas.focus();mythRaf=requestAnimationFrame(mythLoop);});
mythCanvas.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();ignite();}});
mythCanvas.addEventListener('pointerdown',e=>{if(gameArmed){mythCanvas.setPointerCapture(e.pointerId);moveFire(e);}});
function moveFire(e){if(!gameArmed)return;const b=mythCanvas.getBoundingClientRect();mouse.x=(e.clientX-b.left)/b.width;mouse.y=(e.clientY-b.top)/b.height;const target=flameTarget();if(Math.hypot(mouse.x*mw-target.x,mouse.y*mh-target.y)<48)ignite();}
mythCanvas.addEventListener('pointermove',moveFire);
soundButton.addEventListener('click',()=>{musicEnabled=!musicEnabled;if(musicEnabled)startSound();else stopSound();updateSoundLabel();});document.getElementById('skip-game').addEventListener('click',()=>intro.close());enter.addEventListener('click',()=>intro.close());document.getElementById('replay-game').addEventListener('click',openIntro);intro.addEventListener('close',()=>{cancelAnimationFrame(mythRaf);running=false;gameArmed=false;ignited=false;clearTimeout(closeTimer);disposeAudio();if(previousFocus&&previousFocus!==document.body)previousFocus.focus();else document.querySelector('.brand').focus();});mythCanvas.addEventListener('pointermove',e=>{const b=mythCanvas.getBoundingClientRect();mouse.x=(e.clientX-b.left)/b.width;mouse.y=(e.clientY-b.top)/b.height;mouse.active=true;if(!reduce.matches&&!gameArmed&&!ignited){scene.style.setProperty('--mx',`${(mouse.x-.5)*-12}px`);scene.style.setProperty('--my',`${(mouse.y-.5)*-8}px`);}if(!running)drawMyth(elapsed);});mythCanvas.addEventListener('pointerleave',()=>{mouse.active=false;scene.style.setProperty('--mx','0px');scene.style.setProperty('--my','0px');if(!running)drawMyth(elapsed);});mythCanvas.addEventListener('pointerup',e=>{if(e.pointerType!=='mouse')mouse.active=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(mythRaf);mythRaf=0;stopSound();}else if(intro.open&&(running||gameArmed||ignited)){start=performance.now()-elapsed*1000;mythRaf=requestAnimationFrame(mythLoop);}});window.addEventListener('pagehide',disposeAudio);new ResizeObserver(resizeMyth).observe(mythCanvas);applyLanguage();openIntro();
document.querySelectorAll('[data-section]').forEach(node=>node.addEventListener('click',()=>{const section=document.getElementById(node.dataset.section);section.scrollIntoView({behavior:reduce.matches?'instant':'smooth',block:'start'});section.classList.remove('arriving');requestAnimationFrame(()=>section.classList.add('arriving'));}));document.querySelectorAll('.projects article').forEach(card=>{function toggle(){card.setAttribute('aria-expanded',String(card.getAttribute('aria-expanded')!=='true'));}card.addEventListener('click',toggle);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}});});

function unlockIntroMusic(e){if(intro.open&&musicEnabled&&!soundOn&&e.target!==soundButton&&e.target.id!=='skip-game')startSound();}intro.addEventListener('pointerdown',unlockIntroMusic);intro.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')unlockIntroMusic(e);});

const localPlayers=[...document.querySelectorAll("audio,video")];localPlayers.forEach(player=>player.addEventListener("play",()=>localPlayers.forEach(other=>{if(other!==player)other.pause();})));

var activeCaseStage=0;
function renderCaseStage(){const stages=[['01 / CHARACTERS','Building a consistent cast.','Character sheets bring portraits, full-body views, clothing and written profiles into one workspace.'],['02 / VOICE','Giving each character a voice.','Voice previews sit alongside character references, making it possible to compare sound with the intended character.'],['03 / STORYBOARD','Planning the visual sequence.','Storyboard cards organise scene descriptions, shot directions and durations before individual clips are assembled.'],['04 / GENERATION','Moving from plans to clips.','The project is in creative development and has not been released. A watermarked preview is shared here for application purposes only.']];const stage=stages[activeCaseStage||0];document.getElementById('case-stage-label').textContent=tr(stage[0]);document.getElementById('case-stage-title').textContent=tr(stage[1]);document.getElementById('case-stage-description').textContent=tr(stage[2]);document.querySelectorAll('.case-step').forEach((b,i)=>{b.classList.toggle('active',i===(activeCaseStage||0));b.setAttribute('aria-pressed',String(i===(activeCaseStage||0)));});document.querySelector('.case-image-window').dataset.stage=String(activeCaseStage||0);}
document.querySelectorAll('.case-step').forEach(b=>b.addEventListener('click',()=>{activeCaseStage=Number(b.dataset.stage);renderCaseStage();}));renderCaseStage();

var activeThought=0;
function renderThought(){const thoughts=[['MEDIA & STORYTELLING','If creation is shared, where does authorship begin?','I want to explore how intention, interpretation and creative ownership change when people create with AI.'],['INFORMATION & UNDERSTANDING','If AI provides an answer, what does it mean to know?','I want to explore the difference between receiving an answer and understanding its evidence, assumptions and limits.'],['DECISIONS & ACCOUNTABILITY','If a decision is assisted by AI, who is responsible?','I want to explore how people can retain agency and take responsibility for decisions shaped by AI recommendations.']];const data=thoughts[activeThought||0];document.getElementById('thought-context').textContent=tr(data[0]);document.getElementById('thought-title').textContent=tr(data[1]);document.getElementById('thought-copy').textContent=tr(data[2]);document.querySelectorAll('.thought-node').forEach((node,i)=>{node.classList.toggle('active',i===(activeThought||0));node.setAttribute('aria-pressed',String(i===(activeThought||0)));});}
document.querySelectorAll('.thought-node').forEach(node=>node.addEventListener('click',()=>{activeThought=Number(node.dataset.thought);renderThought();}));renderThought();
